### ISSUE TITLE
linker errors for mesh_difference, mesh_remove_intersections

### ISSUE THREAD

**Issue by kasunJKD** [BrunoLevy/geogram#122]
I'm creating a c# wrapper for boolean operations and inflating the mesh (c++ clr/CLI to create a dll). so far every other functions are working but im getting these linker errors for these two functions 

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2028	unresolved token (0A000AAE) "void __cdecl GEO::mesh_difference(class GEO::Mesh &,class GEO::Mesh &,class GEO::Mesh &)" (?mesh_difference@GEO@@$$FYAXAEAVMesh@1@00@Z) referenced in function "public: void __clrcall geogrammanageddll::Geogrammanaged::Boolean_operations(void)" (?Boolean_operations@Geogrammanaged@geogrammanageddll@@$$FQE$AAMXXZ)	geogram_managed_dll	D:\work\geometrylibrary\geogram_managed_dll\geogram_managed_dll.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2028	unresolved token (0A000AB5) "void __cdecl GEO::mesh_remove_intersections(class GEO::Mesh &,unsigned int)" (?mesh_remove_intersections@GEO@@$$FYAXAEAVMesh@1@I@Z) referenced in function "public: void __clrcall geogrammanageddll::Geogrammanaged::fix_mesh_for_boolean_ops_managed(class GEO::Mesh &)" (?fix_mesh_for_boolean_ops_managed@Geogrammanaged@geogrammanageddll@@$$FQE$AAMXAEAVMesh@GEO@@@Z)	geogram_managed_dll	D:\work\geometrylibrary\geogram_managed_dll\geogram_managed_dll.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "void __cdecl GEO::mesh_remove_intersections(class GEO::Mesh &,unsigned int)" (?mesh_remove_intersections@GEO@@$$FYAXAEAVMesh@1@I@Z) referenced in function "public: void __clrcall geogrammanageddll::Geogrammanaged::fix_mesh_for_boolean_ops_managed(class GEO::Mesh &)" (?fix_mesh_for_boolean_ops_managed@Geogrammanaged@geogrammanageddll@@$$FQE$AAMXAEAVMesh@GEO@@@Z)	geogram_managed_dll	D:\work\geometrylibrary\geogram_managed_dll\geogram_managed_dll.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "void __cdecl GEO::mesh_difference(class GEO::Mesh &,class GEO::Mesh &,class GEO::Mesh &)" (?mesh_difference@GEO@@$$FYAXAEAVMesh@1@00@Z) referenced in function "public: void __clrcall geogrammanageddll::Geogrammanaged::Boolean_operations(void)" (?Boolean_operations@Geogrammanaged@geogrammanageddll@@$$FQE$AAMXXZ)	geogram_managed_dll	D:\work\geometrylibrary\geogram_managed_dll\geogram_managed_dll.obj	1	

I dont exactly know why this is happening, since other functions are compiling without any issues.

**Comment by BrunoLevy** [comment]
`1.8.7-rc` is what you get from the git repo.

A quick question to help our investigation: do you encounter any problem when following standard compilation instructions ? [here](https://github.com/BrunoLevy/geogram/wiki/compiling_Windows)

**Comment by kasunJKD** [comment]
no its working

**Comment by BrunoLevy** [comment]
OK (so it eliminates a first potential source of problems). I would have been astonished (because we have continuous integration on all platforms, including Windows, and nothing seems to be broken there).

The error message appears when you link which library ? (I think it is the library that wraps geogram and exposes it to C#, right ?). 
Something important with DLLs under windows is that each compilation unit needs to know which symbol it imports and which symbol it exports. For that, we have a GEOGRAM_API macro that expands to `declspec(DLLexport)` when we compile geogram and that expands to `declspec(DLLimport)` when compiling code that uses geogram, so if a symbol is not found it is related with that. I first sought that I had forgotten to put GEOGRAM_API in the prototype of these functions but I checked and it is there. Another possibility is that there is a more global problem in the compilation and it does not see any symbol but starts barking at the first few ones it does not see. 
Do you have a tool under Windows to inspect the symbols exported by a DLL ?

**Comment by kasunJKD** [comment]
issue is fixed. Thank you for your time, 
what worked for me , after i update the repo even after i cleaned and rebuilt gfx obj has been the old one. so i had to re clone the repo into another dir and compile. maybe a visual studio issue ? but that worked for me
