### ISSUE TITLE
Parallel Delaunay crashes on cube.obj with the Risc-V-64 version

### ISSUE THREAD

**Issue by BrunoLevy** [BrunoLevy/geogram#140]
Parallel Delaunay crashes on cube.obj with the Risc-V-64 version
See  [here](https://github.com/BrunoLevy/geogram/pull/139#issuecomment-2019946179) 
(64 Risc-V cores, 8 vertices)
- it is only the parallel version 
- the debug version catches an out of bound access [here](https://github.com/BrunoLevy/geogram/blob/01f95b34bfd0fa2b03d5f86b2a56a35025d86e48/src/lib/geogram/delaunay/parallel_delaunay_3d.cpp#L166)
- maybe when there are more threads than vertices ?
- but it does not crash on my machine with 8 cores / 16 threads

**Comment by kxxt** [comment]
It also does not crash in riscv64 qemu-user emulation with 32 cpus on a x86_64 host machine. And doesn't crash on the same x86_64 host that has 16 cores and 32 threads.

**Comment by kxxt** [comment]
And if I force it to use 32 cores by hardcoding it `src/lib/geogram/basic/process_unix.cpp`. It also no longer crashes on 64 core riscv64 machine.

**Comment by kxxt** [comment]
Looks like things already go wrong here:

pool_begin and pool_end are both zeros and due to unsignedness the condition `t<pool_end-1` will evaluate to true.

https://github.com/BrunoLevy/geogram/blob/01f95b34bfd0fa2b03d5f86b2a56a35025d86e48/src/lib/geogram/delaunay/parallel_delaunay_3d.cpp#L163-L170

**Comment by BrunoLevy** [comment]
Great, thanks !!!
